// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "../DB/schema.prisma",
  migrations: {
    path: "../DB/migrations",
    seed: "ts-node --project tsconfig.json ../DB/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
